name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'packages/remix-app/**'
      - 'packages/express-backend/**'

jobs:
  deploy-remix:
    name: Deploy remix app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    defaults:
      run:
        working-directory: packages/remix-app
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  build-backend-image:
    name: Build backend image
    runs-on: ubuntu-latest
    concurrency: build-group
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth login
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.fly.io/launch-list-app-express-backend:amd

  deploy-backend:
    name: Deploy backend
    needs: build-backend-image
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --image registry.fly.io/launch-list-app-express-backend:amd
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-trigger-dot-dev:
    name: Deploy trigger.dev
    runs-on: ubuntu-latest
    needs: [deploy-backend, build-backend-image]
    concurrency: deploy-group
    defaults:
      run:
        working-directory: packages/express-backend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          npx trigger.dev@latest deploy
