name: Database migration
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/database/prisma/schema.prisma'

jobs:
  deploy-remix:
    name: Deploy remix app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd packages/database && npx prisma migrate dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
