name: Database migration
on:
  workflow_dispatch:
  # push:
  # branches:
  # - main
  # paths:
  # - 'packages/database/prisma/schema.prisma'

jobs:
  deploy-remix:
    name: Run a database migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - run: cd packages/database && npx prisma migrate dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
