name: Deploy Remix app
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/remix-deploy.yml'
      - 'packages/remix-app/**'
      - 'packages/database/**'

jobs:
  deploy-remix:
    name: Deploy remix app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile Dockerfile.remix-app --config packages/remix-app/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_REMIX_TOKEN }}
